# Generated by Django 5.0.6 on 2024-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('book_title', models.CharField(blank=True, max_length=300, null=True)),
                ('book_details', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_info', models.CharField(blank=True, max_length=100, null=True)),
                ('authorlink', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pages', models.CharField(blank=True, max_length=50, null=True)),
                ('genres', models.CharField(blank=True, max_length=300, null=True)),
                ('num_ratings', models.IntegerField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('rating_distribution', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'book_project',
                'managed': False,
            },
        ),
    ]
